### ISSUE TITLE
"KVM Root PW ändern" -> Unvollständig

### ISSUE THREAD

**Issue by SimbaAddons** [Black-Host-eu/community-wiki#10]
Dieser Beitrag ist unvollständig und nicht genug umschrieben. Kunden könnten sich damit nicht zurecht finden, weshalb eine große Umschreibung nötig ist. Ebenfalls empfehle ich die Anleitung für Virtualizor zum PW reset, sowie passwd für einzelne user.

**Comment by Atomkrieger03** [comment]
Wenn man in der Codebox den kopieren Button nutzt, wird der Comment mit kopiert. Das sollte vielleicht auch angepasst werden.

**Comment by Whity07** [comment]
Done. Danke für die Anmerkungen
