### ISSUE TITLE
"Teamspeak Installation" -> Beitrag fehlt

### ISSUE THREAD

**Issue by SimbaAddons** [Black-Host-eu/community-wiki#11]
Wir suchen Wiki Creator, der Interesse hat diesen Beitrag zu erstellen.

**Comment by Atomkrieger03** [comment]
Ich kann den gerne übernehmen. Du meinst auf einem KVM installieren oder?

**Comment by SimbaAddons** [comment]
Genau, auf KVM :)

**Comment by Atomkrieger03** [comment]
Gut, dann würde ich den Beitrag übernehmen.

**Comment by SimbaAddons** [comment]
Perfekt
