### ISSUE TITLE
"Einrichtungsdauer" -> Beitrag fehlerhaft

### ISSUE THREAD

**Issue by SimbaAddons** [Black-Host-eu/community-wiki#3]
Cloudserver sind direkt nach dem Kauf verfügbar (ohne Wartzeit)
Gameserver fehlt sind aber auch direkt bereit
Sinusbot fehlt sind aber auch direkt bereit
Web-Reseller werden manuell aufgrund von Gewerbeprüfung feigeschaltet.
KVM-Server fehlt auch sind direkt nach dem Kauf bereit

**Comment by Whity07** [comment]
Wird gemacht - sorry!

**Comment by Whity07** [comment]
Habe 60 Sekunden reingeschrieben, weil wir dann safe sind

**Comment by Whity07** [comment]
Erledigt
