### ISSUE TITLE
SinusBot

### ISSUE THREAD

**Issue by Whity07** [Black-Host-eu/community-wiki#6]
Hallo an alle!
Ich würde gerne die SinusBot Section übernehmen.
Hat jemand Ideen, was alles reingeschrieben werden könnte?

Also, ich würde reinschreiben:

- Einrichtungsdauer 
- Login
- TS Einrichtung
habt ihr noch Ideen?

**Comment by Atomkrieger03** [comment]
Musst du die Sinusbot Abteilung übernehmen? Habe damit bereits Angefangen und würde diese gerne vollenden.

**Comment by Whity07** [comment]
Habs gestern schon Simba gesagt, dass ich das gerne machen würde. Von mir aus können wir uns das aufteilen :)

**Comment by Whity07** [comment]
Wurde per DC geklärt - @Atomkrieger03 übernimmt den SinusBot
